services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped

  config-server:
    container_name: config-server
    image: ankanchanda/config-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    depends_on:
      - service-registry
    networks:
      - microservice-network
      - postgres

  service-registry:
    container_name: service-registry
    image: ankanchanda/service-registry:latest
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres

  companyms:
    container_name: companyms
    image: ankanchanda/companyms:latest
    ports:
      - 8081:8081
    depends_on:
      - service-registry
      - config-server
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    container_name: jobms
    image: ankanchanda/jobms:latest
    ports:
      - 8082:8082
    depends_on:
      - service-registry
      - config-server
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

  reviewms:
    container_name: reviewms
    image: ankanchanda/reviewms:latest
    ports:
      - 8083:8083
    depends_on:
      - service-registry
      - config-server
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gatewayms:
    container_name: gatewayms
    image: ankanchanda/gatewayms:latest
    ports:
      - 8084:8084
    depends_on:
      - service-registry
      - config-server
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - postgres

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_container
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - postgres

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: